"""empty message

Revision ID: ea0787d00368
Revises: 
Create Date: 2024-08-10 22:30:32.511312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ea0787d00368'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_follow_followed_id', table_name='follow')
    op.drop_index('ix_follow_follower_id', table_name='follow')
    op.drop_table('follow')
    op.drop_index('ix_board_board_id', table_name='board')
    op.drop_index('ix_board_board_name', table_name='board')
    op.drop_index('ix_board_like', table_name='board')
    op.drop_index('ix_board_star', table_name='board')
    op.drop_index('ix_board_user_id', table_name='board')
    op.drop_table('board')
    op.drop_table('postit_like')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_follower', table_name='user')
    op.drop_index('ix_user_following', table_name='user')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_index('ix_user_nickname', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_postit_Postit_id', table_name='postit')
    op.drop_index('ix_postit_board_id', table_name='postit')
    op.drop_index('ix_postit_like', table_name='postit')
    op.drop_index('ix_postit_user_id', table_name='postit')
    op.drop_table('postit')
    op.drop_table('board_like')
    op.drop_index('ix_star_board_id', table_name='star')
    op.drop_index('ix_star_user_id', table_name='star')
    op.drop_table('star')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('star',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('board_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['board.board_id'], name='star_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='star_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'board_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_star_user_id', 'star', ['user_id'], unique=False)
    op.create_index('ix_star_board_id', 'star', ['board_id'], unique=False)
    op.create_table('board_like',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('board_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.board_id'], name='board_like_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='board_like_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'board_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('postit',
    sa.Column('Postit_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('like', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('board_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.board_id'], name='postit_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='postit_ibfk_1'),
    sa.PrimaryKeyConstraint('Postit_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_postit_user_id', 'postit', ['user_id'], unique=False)
    op.create_index('ix_postit_like', 'postit', ['like'], unique=False)
    op.create_index('ix_postit_board_id', 'postit', ['board_id'], unique=False)
    op.create_index('ix_postit_Postit_id', 'postit', ['Postit_id'], unique=False)
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('follower', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('following', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=True)
    op.create_index('ix_user_id', 'user', ['id'], unique=True)
    op.create_index('ix_user_following', 'user', ['following'], unique=False)
    op.create_index('ix_user_follower', 'user', ['follower'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_table('postit_like',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('postit_like_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['postit_like_id'], ['postit.Postit_id'], name='postit_like_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='postit_like_ibfk_1'),
    sa.PrimaryKeyConstraint('user_id', 'postit_like_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('board',
    sa.Column('board_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('board_name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('star', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('like', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='board_ibfk_1'),
    sa.PrimaryKeyConstraint('board_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_board_user_id', 'board', ['user_id'], unique=False)
    op.create_index('ix_board_star', 'board', ['star'], unique=False)
    op.create_index('ix_board_like', 'board', ['like'], unique=False)
    op.create_index('ix_board_board_name', 'board', ['board_name'], unique=False)
    op.create_index('ix_board_board_id', 'board', ['board_id'], unique=True)
    op.create_table('follow',
    sa.Column('follower_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('followed_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='follow_ibfk_2'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='follow_ibfk_1'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_follow_follower_id', 'follow', ['follower_id'], unique=False)
    op.create_index('ix_follow_followed_id', 'follow', ['followed_id'], unique=False)
    # ### end Alembic commands ###
